spring.application.name=Assignment

server.port=${PORT:8080}
salesforce.client.id=${SALESFORCE_CLIENT_ID}
salesforce.client.secret=${SALESFORCE_CLIENT_SECRET}
salesforce.redirect.uri=https://assignment-l0em.onrender.com/callback